server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 5432
  user: matrix
  dbname: mynest
  sslmode: disable

redis:
  addr: localhost:6379
  password: ""
  db: 0

aria2:
  rpc_url: http://localhost:6800/jsonrpc
  rpc_secret: your-aria2-secret

download:
  save_path: /downloads

auth:
  jwt_secret: ""  # JWT密钥，留空则使用默认值（不推荐）
  default_password: ""  # 默认管理员密码，留空则自动生成